### ISSUE TITLE
Allow custom args in `hikari.internal.ux.print_banner`

### ISSUE THREAD

**Issue by Lunarmagpie** [hikari-py/hikari#1006]
### Summary

Allow any `args` dict to be used in `hikari.internal.ux.print_banner`

### Why is this needed?

It is difficult to add extra information that changes to the banner. For example, a version number. Allowing custom args to be passed in would make this extremely easy,

### Ideal implementation

I think the a kwarg should be added.
```python
async def print_banner(package, allow_color, force_color, args=None):
    if args is None:
       # Set args to the current version
```
Updating args may also work
```python
async def print_banner(package, allow_color, force_color, custom_args=None):
    args = {...}    
    if custom_args:
        args.update(custom_args)
```

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by CircuitSacul** [comment]
Even better, `custom_args.update(original_args)` to allow users to override arguments.
