### ISSUE TITLE
Embed missing `type`

### ISSUE THREAD

**Issue by CircuitSacul** [hikari-py/hikari#1007]
### Summary

Make `Embed.type` reference [this](https://discord.com/developers/docs/resources/channel#embed-object-embed-types)

### Why is this needed?

It's part of the discord API

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by FasterSpeeding** [comment]
> Embed types are "loosely defined" and, for the most part, are not used by our clients for rendering. Embed attributes power what is rendered. Embed types should be considered deprecated and might be removed in a future API version.

Emphasis on the "deprecated and might be removed in a future API version." part

**Comment by CircuitSacul** [comment]
> > Embed types are "loosely defined" and, for the most part, are not used by our clients for rendering. Embed attributes power what is rendered. Embed types should be considered deprecated and might be removed in a future API version.
> 
> Emphasis on the "deprecated and might be removed in a future API version." part

I completely missed that, sorry. Ig I'll have to find a different way to determine the type.

**Comment by davfsa** [comment]
> I completely missed that, sorry. Ig I'll have to find a different way to determine the type.

Events will no longer have a "type" in the future. You can get all the information you need from inspecting the different attributes in `Embed`
