### ISSUE TITLE
Add a guides section to the docs for newcomers to the library

### ISSUE THREAD

**Issue by HyperGH** [hikari-py/hikari#1064]
### Summary

Ideally this should be located in a prominent section of the documentation, and touch on common topics on how to get a bot running. If given the go-ahead, I (and many others) would contribute to this and add guides on specific topics.

### Why is this needed?

It can be argued that guides do not belong in documentation, or that they should be located in-line along with the auto-generated documentation, but I still feel that some form of centralized step-by-step instructions for newcomers would help ease the burden of figuring out hikari, as currently I feel that the weakest point of hikari is approachability.

### Ideal implementation

Something along the lines of what lightbulb does currently with it's documentation, but there are many more examples of this: https://hikari-lightbulb.readthedocs.io/en/latest/guide.html

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by FasterSpeeding** [comment]
This feels similar to #835

**Comment by HyperGH** [comment]
I would argue it is different to a getting started section, as instead of providing a general starting point to the library, this aims to target specific topics (E.g. commands, components, embeds), while a getting started section is more analogous to [lightbulb's getting](https://hikari-lightbulb.readthedocs.io/en/latest/getting-started.html) started page:

**Comment by FasterSpeeding** [comment]
> I would argue it is different to a getting started section, as instead of providing a general starting point to the library, this aims to target specific topics (E.g. commands, components, embeds), while a getting started section is more analogous to [lightbulb's getting started](https://hikari-lightbulb.readthedocs.io/en/latest/getting-started.html) page:

ngl i don't really see the difference there. those are all topics that would be covered by a getting started section for Hikari and lightbulb's "getting started" page isn't what I would've had in mind for a getting started section for Hikari at all since you couldn't ever give an explanation of the most import functionalities exposed by Hikari in such a small page and hikari already has an equivalent to that lightbulb page in the README

**Comment by HyperGH** [comment]
Alright, closing it then! :)

**Comment by FasterSpeeding** [comment]
We're going to do add a getting started section to the docs eventually, just nobody's gotten around to it yet and it can't be worked on until the current open docs pr is done anyways.

**Comment by HyperGH** [comment]
> We're going to do add a getting started section to the docs eventually, just nobody's gotten around to it yet and it can't be worked on until the current open docs pr is done anyways.

Understood, thanks!
