### ISSUE TITLE
Accept yarl.URL as a resource.

### ISSUE THREAD

**Issue by thesadru** [hikari-py/hikari#1079]
### Summary

Take `yarl.URL` where a `hikari.URL` could be accepted and cast it to `hikari.URL` internally.

### Why is this needed?

Sometimes people may want to build a URL using yarl.

### Ideal implementation

Extra case to handle in the same place Resourceish is handled.

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by davfsa** [comment]
This would add `yarl` as a direct dependency to hikari, but wouldnt add much more functionality.

You could just use this for now:
```py
yarl_url = yarl.URL("https://www.hikari-py.dev/logo.png")

hikari_url = hikari.URL(str(yarl_url))
# hikari_url can then be used wherever you need it
```
