### ISSUE TITLE
Fix hikari.Permissions bitwise operation examples

### ISSUE THREAD

**Issue by lilapela** [hikari-py/hikari#1133]
### Summary

In the docs, the description for an IntFlag enum gives this example:

```
if my_perms & (Permissions.MANAGE_CHANNELS | Permissions.MANAGE_GUILD):
    print("I have the permission to both manage the guild and the channels in it!")
```

The expression in the example evaluates to true when my_perms contains either permission, not both permissions.

### Why is this needed?

Some of the examples in the docs are misleading.

Like the description for the hikari.Intents enum, the description for hikari.Permissions should make it more clear how combining the & and == operators allows you to check that the entire intersection of two sets of enums are in another set:

```
if my_perms & (Permissions.MANAGE_CHANNELS | Permissions.MANAGE_GUILD) == Permissions.MANAGE_CHANNELS | Permissions.MANAGE_GUILD):
    print("I have the permission to both manage the guild and the channels in it!")
```

I think a more clear and concise example would be:

```
if my_perms & required_perms == required_perms
    print("I have all of the required permissions!")
```

Also the docs said that If the permission is not present, the bitwise xor will return a non-zero value, otherwise if it is present, it will return 0.
Actually the bitwise xor operation only returns a nonzero value whenever both operands are not exactly the same, and the example in the docs will only work if both my_perms and required_perms are made of just 1 permission.

### Ideal implementation

To demonstrate how to check whether all the required permissions are present, put something like
```
if my_perms & required_perms == required_perms
    print("I have all of the required permissions!")
```

Bitwise Xor:
For hikari.Permissions, I can't really think of a practical application. Technically if we wanted to fix the example in the docs we would do:

```
missing_perms = (my_perms ^ required_perms) & required_perms
if (missing_perms):
    print(f"I'm missing these permissions! {missing_perms}")
```

But maybe this should just be removed because this is a really specific example, and we're not trying to explain how bitwise operators work. lmk what you think thanks

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by davfsa** [comment]
Thank you for the amazing bug report. You have indeed found a bug in the documentation, as those examples are wrong. Will have a look at them again and edit them accordingly :+1:

**Comment by lilapela** [comment]
I realized that the bitwise xor example can be made even simpler by doing the bitwise set difference operation
```
missing_perms = ~my_perms & required_perms
if (missing_perms):
   print(f"I'm missing these permissions: {missing_perms}")
```
