### ISSUE TITLE
message.get_channel() causes AssertionError in VCs

### ISSUE THREAD

**Issue by Le0Developer** [hikari-py/hikari#1178]
### Steps to reproduce

1. send a message in a text in voice channel
2. call message.get_channel()

### Expected result

No AssertionError

### Actual result

AssertionError

### System info

```shell
hikari (2.0.0.dev109) [HEAD]
located at /home/pi/.local/lib/python3.10/site-packages/hikari
CPython 3.10.2 GCC 10.2.1 20210110
Linux rasp-3b-02 5.10.92-v7+ #1514 SMP Mon Jan 17 17:36:39 GMT 2022 armv7l
```

### Further info

```py
AssertionError: Cached channel ID is not a TextableGuildChannel, but a GuildVoiceChannel!
  File "threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "clend/guild/components/slowmode.py", line 19, in on_message_create
    channel = event.get_channel()
  File "hikari/events/message_events.py", line 277, in get_channel
    assert channel is None or isinstance(
```
![image](https://user-images.githubusercontent.com/40232557/171638576-6412b81a-9b9b-436d-a8ae-0da2449cf54a.png)

### Checklist

- [X] I have made sure to remove ANY sensitive information (bot token, passwords, credentials, personal details, etc.).
- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by davfsa** [comment]
Fixed as of #1179
