### ISSUE TITLE
Message Event Bug

### ISSUE THREAD

**Issue by kshgr** [hikari-py/hikari#1300]
### Steps to reproduce

1. Create a GuildMessageCreateEvent
2. Take the value of event.content
3. type(event.content)
4. Send a message in a Guild 
5. Check Terminal

### Expected result

type(event.content) should be returned as a string for all text messages in server 

### Actual result

type(event.content) returns None type for all messages in server.

### System info

```shell
hikari (2.0.0.dev111) [2d0c77b5]
located at C:\Users\kushagra\AppData\Local\Programs\Python\Python310\lib\site-packages\hikari
CPython 3.10.7 MSC v.1933 64 bit (AMD64)
Windows Kushagra-Z-Book 10 10.0.22000 AMD64 Intel64 Family 6 Model 154 Stepping 3, GenuineIntel
```

### Checklist

- [X] I have made sure to remove ANY sensitive information (bot token, passwords, credentials, personal details, etc.).
- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by Fridenity** [comment]
Have you perhaps enabled message content intents in your bot's developer portal?

**Comment by kshgr** [comment]
You can alternatively refer to my tutorial video during which this bug was found
https://www.youtube.com/watch?v=jlhZXFfS40s
Timestamp - 9:25 to 10:15

**Comment by kshgr** [comment]
> Have you perhaps enabled message content intents in your bot's developer portal?

All intents are enabled and the bot was working alright with GuildMessageCreateEvent until last time.

**Comment by novanai** [comment]
You have not, however, enabled intents within the bot's constructor in your code.

you need to add `intents=hikari.Intents.MESSAGE_CONTENT`
(https://www.hikari-py.dev/hikari/intents.html#hikari.intents.Intents.MESSAGE_CONTENT)

**Comment by kshgr** [comment]
> You have not, however, enabled intents within the bot's constructor in your code.
> 
> you need to add `intents=hikari.Intents.MESSAGE_CONTENT` (https://www.hikari-py.dev/hikari/intents.html#hikari.intents.Intents.MESSAGE_CONTENT)
> 
> Edit: Although watching more of the video, when you start using lightbulb you add all intents

Alright thanks
Is there a recent change that requires this to be done?

I do not remember this being an issue a couple of months back.

**Comment by novanai** [comment]
Yes, Discord made message content a privileged intent. You can read more here: https://support-dev.discord.com/hc/en-us/articles/4404772028055-Message-Content-Privileged-Intent-FAQ

**Comment by kshgr** [comment]
Great, thank you for your help! I will be sure to pass on the message in the next video.
