### ISSUE TITLE
Add option to supress optimization warning message

### ISSUE THREAD

**Issue by yakMM** [hikari-py/hikari#1446]
### Summary

The warning introduced by #1431 can be annoying in some context (for example code analysis that needs runtime evaluation, like [slotscheck](https://slotscheck.readthedocs.io/en/latest/)).

I assume there may be some other use cases for wanting to disable the warning (dev platform running without optimization, etc)

### Why is this needed?

Other features can be disabled iirc, like the check for update call or the banner. More choice seems better in that case.

### Ideal implementation

Using the same mechanism as banner deactivation?

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by davfsa** [comment]
We run `slotscheck` on our CI and dont see any issues with that (https://github.com/hikari-py/hikari/actions/runs/3833692249/jobs/6525422008#step:9:1; latest run at the time of writing) and I dont see how it could cause an issue. We could add an option to disable it, as it is more in-line with the rest of the bot structure, I just forgot about it. But would you mind explaining your issue more in detail?

**Comment by yakMM** [comment]
Yes I have a run guard, but not for the bot declaration. The warning is emitted when the bot object is created, not when the application is run.

There is no need in actually creating a bot object in a library, but it's different for an application: having the bot object as a global variable is a quicker approach than dependency injection for example.

Anyways, my use case was just there as an example, I don't want to make a point from it, it could be worked around.

This issue is mostly about "Hey other features can be activated / disabled (banner, update checks), why not this warning?" - and to trace other users possibly complaining about the warning.

**Comment by yakMM** [comment]
Regarding using run guards:

Consider the basic example from the README:

```py
import hikari

bot = hikari.GatewayBot(token="...")

@bot.listen()
async def ping(event: hikari.GuildMessageCreateEvent) -> None:
    """If a non-bot user mentions your bot, respond with 'Pong!'."""

    # Do not respond to bots nor webhooks pinging us, only user accounts
    if not event.is_human:
        return

    me = bot.get_me()

    if me.id in event.message.user_mentions_ids:
        await event.message.respond("Pong!")

bot.run()
```

Type guard would usually be implemented only to cover the bot.run call, else you have to put all the code under the if:

```py
import hikari

bot = hikari.GatewayBot(token="...")

@bot.listen()
async def ping(event: hikari.GuildMessageCreateEvent) -> None:
    """If a non-bot user mentions your bot, respond with 'Pong!'."""

    # Do not respond to bots nor webhooks pinging us, only user accounts
    if not event.is_human:
        return

    me = bot.get_me()

    if me.id in event.message.user_mentions_ids:
        await event.message.respond("Pong!")

if __name__ == "__main__":
    bot.run()
```

In this example, the warning will be emitted in any runtime evaluation (including a slotscheck run, for example.

Wouldn't it be more appropriate to put the warning in the `run `call instead of the `__init__`, at least?
