### ISSUE TITLE
Pottential speedup: ujson or orjson

### ISSUE THREAD

**Issue by davfsa** [hikari-py/hikari#1453]
A potential speedup we could add to the mix is [ujson](https://pypi.org/project/ujson/), which after some quick testing, it seems to be a drop in replacement to the standard libraries implementation, but performs a lot better, which is already noticeable on startup, so could be even more significant for large bots, so might be worth looking into:

*stdlib:*
![image](https://user-images.githubusercontent.com/29100934/210639480-78573135-124d-4d4c-b470-cd03fb90dcad.png)

*ujson:*
![image](https://user-images.githubusercontent.com/29100934/210639592-554c8254-40d3-4784-9a81-0105b925c30c.png)

*Typehints are provided through [typeshed](https://github.com/python/typeshed/blob/main/stubs/ujson/ujson.pyi), so shouldnt have an issue with typecheckers*

----

If you want to provide feedback on this issue and test it yourself, you can easily do it by adding the following lines to your bot script (after installing ujson):

```py
import ujson
from hikari.internal import data_binding

data_binding.dump_json = ujson.dumps
data_binding.load_json = ujson.loads
```

**Comment by Lunarmagpie** [comment]
Have you looked into [orjson](https://github.com/ijl/orjson)? orjson is a larger library compared to ujson but its marginally faster in decoding benchmarks I think are more applicable to this project and its encoding speed is over 2x faster than ujson in all the benchmarks. 

https://github.com/ultrajson/ultrajson#benchmarks

**Comment by davfsa** [comment]
I did in fact look at it, but it seems to perform slower than ujson in our case. I re-ran the benchmarks provided by `ujson` [here](https://github.com/ultrajson/ultrajson/blob/main/tests/benchmark.py) and did see `orjson` performing considerably better, but when it comes to a Discord workload, `ujson` shows better performance. I havent really looked into it (a bit why I opened this issue instead of a PR).

You can test it out yourself by replacing this specific line with `send_bytes`
https://github.com/hikari-py/hikari/blob/deb3ed15b7adfb2581f9869048c50586563c4d5c/hikari/impl/shard.py#L201

If anyone can run performance tests on their bots, please feel free to share, they are greatly welcome!

---

PS: While looking into this, I stumbled on this issue from Sanic regarding the same results I encountered: https://github.com/sanic-org/sanic/issues/1479#issuecomment-932960095

**Comment by parafoxia** [comment]
So I've experimented on Carberretta, and the differences are pretty minimal. I tried 3 times with each, and these were the average results:

* Normal: 2.22s
* ujson: 2.17s
* orjson: 2.25s

I reckon some more data could be helpful, but there doesn't seem to be any major differences. The differences are smaller on a bot with more parts at the very least.

**Comment by davfsa** [comment]
Since `orjson` was brought up, I experimented a bit with it and came up [this branch](https://github.com/davfsa/hikari/tree/task/orjson).

I am still not fully happy with the outcome and have some plans to improve it even more, bringing in support to be able to pass `json.loads` and `json.dumps` singnature compliant functions.

Regardless, any testing on that branch (specially in large bots, if possible) would be welcome and appreciated!

**Comment by parafoxia** [comment]
I feel like this line should be changed or removed, as most bots will be running with optimisation flag 1 or 2, which remove assert statements.

https://github.com/hikari-py/hikari/compare/master...davfsa:hikari:task/orjson#diff-9aeb579dd7fd79080ace8defc3a3d27bf3855168dd1e4e7968727d5689d93fb3R431
