### ISSUE TITLE
Add startup callback and shutdown callback traits for RESTBot

### ISSUE THREAD

**Issue by Lunarmagpie** [hikari-py/hikari#1481]
### Summary

Add startup callback and shutdown callback traits for RESTBot.

### Why is this needed?

Command handlers have a hard time relying on any impl of InteractionServer right now because they have no way to add or remove callbacks when the server is opened and shutdown. If these traits could be required by command handlers it would make modularity easier.

### Ideal implementation

Implement these two traits.

```python
class StartupCallbackAware(Protocol):
    def add_startup_callback(
        self, callback: Callable[[Self], Coroutine[Any, Any, None]], /
    ) -> None:
    ...

    def remove_startup_callback(
        self, callback: Callable[[Self], Coroutine[Any, Any, None]], /
    ) -> None:
    ...

class ShutdownCallbackAware(Protocol):
    def add_shutdown_callback(
        self, callback: Callable[[Self], Coroutine[Any, Any, None]], /
    ) -> None:
    ...

    def remove_shutdown_callback(
        self, callback: Callable[[Self], Coroutine[Any, Any, None]], /
    ) -> None:
    ...
```

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by davfsa** [comment]
This was added back when the feature was implemented https://github.com/hikari-py/hikari/commit/aa8ba84ff8eaf2021f64a1444acb9d3f8d571e69#diff-518828fddf5e8392914a3722a610b68d37cb23eba91cc7c9cfa04308f9591660R572-R642
