### ISSUE TITLE
Forum channels unrecognised

### ISSUE THREAD

**Issue by lionel-panhaleux** [hikari-py/hikari#1518]
### Steps to reproduce

1. Connect to a guild with a Forum channel
2. Use bot.rest.fetch_guild_channels
3. You get an error because the channel type is not handled: `hikari.errors.UnrecognisedEntityError: Unrecognised channel type 15`

### Expected result

Get the list of channels, or at worst (or as a first iteration) a partial list excluding the forum channels instead of an error.

### Actual result

```
  File "venv/lib/python3.9/site-packages/hikari/impl/rest.py", line 2396, in fetch_guild_channels
    channel_sequence = [self._entity_factory.deserialize_channel(channel_payload) for channel_payload in response]
  File "venv/lib/python3.9/site-packages/hikari/impl/rest.py", line 2396, in <listcomp>
    channel_sequence = [self._entity_factory.deserialize_channel(channel_payload) for channel_payload in response]
  File "venv/lib/python3.9/site-packages/hikari/impl/entity_factory.py", line 1035, in deserialize_channel
    raise errors.UnrecognisedEntityError(f"Unrecognised channel type {channel_type}")
hikari.errors.UnrecognisedEntityError: Unrecognised channel type 15
```

### System info

```shell
hikari (2.0.0.dev108) [6dbab9a6]
located at venv/lib/python3.9/site-packages/hikari
CPython 3.9.2 GCC 10.2.1 20210110
Linux vps-cc5cbcc9 5.10.0-11-cloud-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64
```

### Checklist

- [X] I have made sure to remove ANY sensitive information (bot token, passwords, credentials, personal details, etc.).
- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by novanai** [comment]
The problem is you're using hikari version dev108, which is very outdated. Please update to the latest version (dev116) and this will work fine :)

**Comment by lionel-panhaleux** [comment]
Thanks for the quick answer and yeah, sorry, I figured it out after checking the code, my bad. Works now :-)
