### ISSUE TITLE
Add support for comparing roles

### ISSUE THREAD

**Issue by shahriyardx** [hikari-py/hikari#1605]
### Summary

Currently we can't compare a role directly by saying Role1 > Role2 

### Why is this needed?

So comparing roles becomes easier

### Ideal implementation

To be decided.

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by davfsa** [comment]
This has been deliberately not added, as there is no way to realistically say "one role is greater than another".

To check for role "order", you can follow the following rules:

1. Compare their position attribute
2. If they have the same position, compare them by ID
