### ISSUE TITLE
Option to only cache the bot member

### ISSUE THREAD

**Issue by Le0Developer** [hikari-py/hikari#1678]
## Summary

This requests aims to introduce a new option for enabling the members cache ONLY for the bot member.
Similar to `CacheComponents.ME` but for the member.

## Why is this needed?

The bot member is very useful for permissions calculations and enabling the members caches every member, increasing memory consumption and CPU consumption on startup.

## Ideal implementation

see pr :)

**Comment by FasterSpeeding** [comment]
This isn't a bug, the ME cache component is a separate cache store (completely unrelated to members). What you're requesting is a separate configuration for the MEMBERS cache store.
