### ISSUE TITLE
Consider using mkdocs material

### ISSUE THREAD

**Issue by hypergonial** [hikari-py/hikari#1806]
### Summary

We should consider using [mkdocs material](https://squidfunk.github.io/mkdocs-material/) for the documentation.

I have the following reasons as to why:
- Much better search that is very responsive
- Nicer looking interface
- The entire site doesn't have to reload for every navigation (Instant Navigation)
- Highly extensible and customizable
- Properly builds `objects.inv` so it is actually usable by other repos
- Supports advanced markdown features such as [tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/) & admonishments ([full list](https://squidfunk.github.io/mkdocs-material/reference/))
- Is also [supported by readthedocs](https://docs.readthedocs.io/en/stable/intro/getting-started-with-mkdocs.html) so documentation versioning & deployment should be simple

### Why is this needed?

The current documentation is very slow to load, the search is not very responsive (if it works at all), and `objects.inv` is almost completely unusable by other documentation generators.

### Ideal implementation

Something like [this](https://arc.hypergonial.com/)

If given the go-ahead, **I'd be willing to work on a PR** to switch the documentation to mkdocs-material with a similar configuration as the one I use, linked above.

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by parafoxia** [comment]
I can vouch for MkDocs Material -- I use it myself and it's wonderful.

**Comment by hypergonial** [comment]
> I can vouch for MkDocs Material -- I use it myself and it's wonderful.

Way ahead of you already, PR is almost done :p

**Comment by parafoxia** [comment]
Oh yeah so there is, didn't see that lmao.
