### ISSUE TITLE
Add an `old_x` attribute to update events

### ISSUE THREAD

**Issue by Tmpod** [hikari-py/hikari#198]
### Summary

There should be an attribute in update related events that point to the latest "old" version of said entity in cache, None otherwise.

### Problem

Currently it's quite impracticable to know what changed with `XUpdateEvent` events, since the cache is updated before the event is dispatched to the listeners/subscribers. To achieve the desired effect, one would have to change the whole cache implementation so that the cache is updated after the events are dispatched, which is quite cumbersome.

Having the "possible" older version of the updated entity is quite useful because you're able to know what part of it changed and so correctly trigger whatever logic you want. Without this, it becomes much harder to execute some routine whenever, let's say, a member is muted, or a guild has its logo changed.

### Ideal implementation

I believe it would probably be best to simply add a field/attribute to those event classes that contain the cached entity before it is updated, possibly named `old_x` (`old_channel`, `old_role`, etc).   

One issue I see with this is an extra hit on cache, which can possibly be more precious than this, but I also believe if someone is needing that level of optimisation, they probably know their way around quite well and have written their own implementation of stuff.

### Checklist

- [x] I have searched the issue tracker and have made sure it's not a duplicate.

**Comment by nekokatt** [comment]
sounds good to me.

**Comment by Reliku** [comment]
I'll take care of it.
