### ISSUE TITLE
UnicodeEmoji.parse should actually check if its a valid emoji

### ISSUE THREAD

**Issue by davfsa** [hikari-py/hikari#270]
### Steps to reproduce
```py
import hikari

hikari.Emoji.parse("some text") # This should probably error
```

### System info
```
hikari v2.0.0.dev80 36111793e381363db845c3b9bb0d41163fe72605
located at /home/davfsa/coding/hikari/.venv/lib/python3.8/site-packages/hikari
CPython 3.8.2 GCC 9.3.0
Linux carbono 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64
```

### Further info
I found this module on PyPI [emoji](https://pypi.org/project/emoji/) that might be helpful as it contains a list of all the unicode emojis: `emoji.UNICODE_EMOJI`

### Checklist

- [x] I have made sure to remove ANY sensitive information (bot token, passwords,
      credentials, personal details, etc).
- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by nekokatt** [comment]
How will you determine what is a valid emoji? They are just characters. Discord does not appear to define that formally.

Remember this is not only twemoji, as non twemoji emotes work too.

**Comment by davfsa** [comment]
Hmmm. Good point, I just thought that we might need to do something about being able to parse any string into the UnicodeEmoji object.

I opened it because in the example files we have available in the repo, there is a path that leads to parsing the emoji using `hikari.Emoji.parse(string)`.

As @FasterSpeeding found, you can parse anything into the UnicodeEmoji and it will treat it as correct. Then, when you try to upload the emoji as an attachment, it will try to fetch the emoji from the twemoji repo, causing it to fail and print out a nasty error to the console (raw body of the github 404 not found response) and it might not be intuitive for some end users on what to do (some might even expect us to be handling that)

**Comment by nekokatt** [comment]
So that would still happen if you passed a valid emoji that just wasn't a twemoji, right?

It'd be simpler to just document this clearly tbh.

**Comment by nekokatt** [comment]
We could add in optional support and make it an optional extra, if you want to do this.

For example:
```py
pip install hikari[emojis,speedups]
```

**Comment by davfsa** [comment]
Closing this for now. If people request this in the future, will add it.
