### ISSUE TITLE
Remove serialize entity factory methods and add builder classes

### ISSUE THREAD

**Issue by FasterSpeeding** [hikari-py/hikari#308]
### Summary
Remove the embed and channel overwrite serialize methods from the entity factory and add embed builder and overwrite builder models to be consistent with keeping models immutable

### Problem
Models shouldn't be mutable and having serialize methods for 2 models is inconsistent and unnecessary

### Ideal implementation
See summary 

### Checklist

- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by davfsa** [comment]
Closing this for now as its not a priority, will open in the future if we see fit
