### ISSUE TITLE
Template objects + endpoints

### ISSUE THREAD

**Issue by davfsa** [hikari-py/hikari#322]
https://discord.com/developers/docs/resources/template
https://github.com/discord/discord-api-docs/commit/943c6f530b45798eac1c58874da6fa3f3b4b92e6

**Comment by FasterSpeeding** [comment]
are these being worked on?

**Comment by davfsa** [comment]
> are these being worked on?

Was planning on, but I decided to move this back to focus on more important tickets, feel free to work on if if you want

**Comment by davfsa** [comment]
@FasterSpeeding added a new link to the issue as there was new info added

**Comment by FasterSpeeding** [comment]
Closed by #392
