### ISSUE TITLE
Search Guild Members REST Endpoint

### ISSUE THREAD

**Issue by davfsa** [hikari-py/hikari#323]
~~https://discord.com/developers/docs/resources/guild#list-guild-members~~
https://github.com/discord/discord-api-docs/pull/1577

**Comment by FasterSpeeding** [comment]
are these being worked on?

**Comment by davfsa** [comment]
I just realized this is already an endpoint, will close :sweat_smile:

**Comment by FasterSpeeding** [comment]
This was likely meant to be referring to https://github.com/discord/discord-api-docs/pull/1577 rather than the normal paginated list members endpoint just mislinked

**Comment by ahnaf-zamil** [comment]
Can someone explain what this issue is about? Do we basically need to work a REST endpoint that we can use to search for guild members? It's kinda similar to lightbulb's get utility command

**Comment by davfsa** [comment]
There is a chunked rest endpoint that we havent implemented yet (check FasterSpeeding's comment). This is fairly easy to do, its just @FasterSpeeding told me he was going to work on it, so I didnt.
