### ISSUE TITLE
Applications methods.

### ISSUE THREAD

**Issue by davfsa** [hikari-py/hikari#33]
In `applications.py`, implement:
- `Application#fetch_guild`
- `Application#fetch_guild_preview`

These should be documented and tested.

**Comment by ahnaf-zamil** [comment]
I would like to work on this issue

**Comment by FasterSpeeding** [comment]
> I would like to work on this issue

Go ahead 👍

**Comment by ahnaf-zamil** [comment]
Close this issue as https://github.com/hikari-py/hikari/pull/757 got merged
