### ISSUE TITLE
Role tags

### ISSUE THREAD

**Issue by davfsa** [hikari-py/hikari#345]
https://github.com/discord/discord-api-docs/issues/1537#issuecomment-656432643

**Comment by FasterSpeeding** [comment]
Do we know if this has been rolled out to all guilds properly yet?

**Comment by davfsa** [comment]
As far as I'm aware, no. But we can still implement them since the API is returning the values for them

**Comment by FasterSpeeding** [comment]
still seems misleading to have something implemented that'll only appear in some guilds but eh that's discord's api for you

**Comment by davfsa** [comment]
https://github.com/discord/discord-api-docs/issues/1537#issuecomment-733942178 fully implemented 👍
