### ISSUE TITLE
Ban method for guild member object

### ISSUE THREAD

**Issue by ahnaf-zamil** [hikari-py/hikari#348]
### Summary
Right now, if we want to ban a member, we have to use the bot's rest. But to make things easier, we can just call the ban
method on a member object and it should work. This is a follow up/part of this [issue](https://github.com/hikari-py/hikari/issues/37)

### Problem
Reduces the amount of work required to ban a member from a guild

### Ideal implementation
Make an asynchronous function for banning the member and it should call the bot's rest methods which is
required for banning the member. This method should take the `reason` and `delete_message_days` arguments.

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by ahnaf-zamil** [comment]
I am currently working on this issue

**Comment by davfsa** [comment]
Im going to close this one as an extension of #37
