### ISSUE TITLE
Guilds methods

### ISSUE THREAD

**Issue by davfsa** [hikari-py/hikari#37]
Methods and properties should be added to guild models where appropriate.

These may take the shape of the following, but this is just a recommendation and should be at the developer's discretion.

Also, these should be tested and fully documented.

- `GuildWidget#fetch_channel`
- `Member`
    - `#fetch_user`
    - `#fetch_roles`
    - ~`#ban`~
    - `#kick`
    - `#add_roles`
    - `#remove_roles`
- `MemberPresence`
    - `#fetch_user`
    - `#fetch_member`
- `GuildIntegration`
    - `#fetch_user`
    - `#fetch_member` (?)
    - `#sync` (?)
- `GuildMemberBan`
    - Rename to `GuildBan`
    - `#unban`
- `GuildPreview`
    - `#fetch_guild`
- `Guild`
    - `#edit`
    - `#ban`
    - `#kick`
    - `#unban`
    - `#fetch_owner`
    - `#fetch_afk_channel`
    - `#fetch_roles` async iter
    - `#fetch_emojis`
    - `#fetch_widget_channel`
    - `#fetch_system_channel`
    - `#fetch_rules_channel`
    - `#fetch_public_updates_channel`
    - `#update_voice_state`
    - `$text_channels`
    - `$voice_channels`
    - `$categories`
    - `$news_channels`
    - `$store_channels`
    - `#add_channel`
    - `#add_category` (redundant?)
    - `#remove_channel`
    - `#remove_category` (redundant?)

**Comment by ahnaf-zamil** [comment]
Lemme try and see what I can do

**Comment by ashwinvin** [comment]
Seems like pretty easy thing to do. Can I attempt at doing this?
