### ISSUE TITLE
Ignore new GUILD_INTEGRATIONS_UPDATE as it dupes existing event

### ISSUE THREAD

**Issue by davfsa** [hikari-py/hikari#396]
```
 2020-12-16 16:03:28,317 hikari: ignoring unknown event GUILD_INTEGRATIONS_UPDATE:
    {'guild_id': '265828729970753537'}
```

**Comment by FasterSpeeding** [comment]
GUILD_INTEGRATIONS_UPDATE isn't useful, it just dupes the newer integration events without providing any useful information

**Comment by davfsa** [comment]
We can have a null handler to stop it from logging at least

**Comment by FasterSpeeding** [comment]
> We can have a null handler to stop it from logging at least

not too sure that's necessary since this is only debug logging anyway but if you'd rather it didn't then sure
