### ISSUE TITLE
Multiple version documentation

### ISSUE THREAD

**Issue by davfsa** [hikari-py/hikari#410]
We should provide the documentation of all the versions that are released.

There should be UI to switch between the different versions of the documentation and proper management of the documentation versions. There should also be 2 special tags: `latest` and `stable` to allow fast access to the documentation of both development and stable release respectively.

*Note: This is not necessary until before release of version 2.0.0*

**Comment by Forbidden-A** [comment]
I'd say latest and stable instead of dev and latest

**Comment by Forbidden-A** [comment]
> I'd say latest and stable instead of dev and latest

Unless I'm understanding this wrong

**Comment by davfsa** [comment]
> I'd say latest and stable instead of dev and latest

Edited :+1:

**Comment by FasterSpeeding** [comment]
Might be worth it making a separate docs repo for this, could also possibly do something with different deployed environments if we wanted to get real fancy

**Comment by davfsa** [comment]
> Might be worth it making a separate docs repo for this, could also possibly do something with different deployed environments if we wanted to get real fancy

Might be useful. This also means we could move the docs from `https://github.io/hikari-py/hikari` into `https://github.io/hikari-py`. But yea, good idea :+1:

**Comment by davfsa** [comment]
Little update on this, it might take a while.

I have noticed a lot of issues with the current website and will be remaking it from the ground up. Small prs might come in once in a while, but don't expect anything soon.

**Comment by davfsa** [comment]
Blocked by #808
