### ISSUE TITLE
Better replies

### ISSUE THREAD

**Issue by A5rocks** [hikari-py/hikari#418]
### Summary
`Message#reply` has unintuitive behaviour, and `rest#edit_message` does not have a `reply_mention` argument (crucial to make sure not to wipe mention).

### Problem
Problem 1) `Message#reply` currently does not "reply" unless you do `message.reply('hi there', message_reply=message)`.

Problem 2) You cannot edit a message that is a reply without making it ping (due to `reply_mention` not being an argument you can pass in).

### Ideal implementation
`Message#reply` is for replies, `Message#respond` is not. https://github.com/mewna/catnip does this, making code like this possible (warning: Java): https://github.com/Faith1sGay/Oreo/blob/main/src/main/java/io/github/faith1sgay/oreo/Oreo.java#L85-L87

Also, making `reply_mention` an argument in `Message#edit` (as well as `RestApp#edit_message`).

### Checklist
- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by davfsa** [comment]
Good suggestion, was planning on doing the first point already, but was kind of busy with all the refactoring that we have been doing. Second one is a bug, sorry about that one. Will get those implemented/fixed 👍

**Comment by davfsa** [comment]
An issue has been created with discord to address a part of this problem (having to specify no-ping even if not pinging initially) https://github.com/discord/discord-api-docs/issues/2474
