### ISSUE TITLE
Consistency fixup for when we use Protocols vs Abstract Classes

### ISSUE THREAD

**Issue by FasterSpeeding** [hikari-py/hikari#431]
### Summary
We're currently inconsistently using Protocols and Abstract Classes for client interface definitions (see `hikari.api.entity_factory.EntityFactory` vs `hikari.api.event_factory.EventFactory`).

### Problem
Some client interfaces are protocls whereas others are abstract classes.

### Ideal implementation
My ideal implementation would be switching to protocols for these as the reasons for using abstract classes are either insignificant (e.g. having runtime errors if a incomplete abc is used) or not really applicable to clients (e.g. having subclass checks which allow for more performant instance checking compared to runtime checkable protocols) while protocols make our typing for clients generally more flexible due to not enforcing direct inheritance.

### Checklist

- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by Rvmy** [comment]
hikari.api.entity_factory.EntityFactory

**Comment by davfsa** [comment]
`hikari.api.event_factory.EventFactory` should not be a protocol, but an `abc.ABC` instead. All the functions there should also be marked as `abc.abstractmethod`.

I have also been considering changing all the `typing.Protocols` to `ABC`'s too to force everything to be implemented

**Comment by davfsa** [comment]
Closed by #434
