### ISSUE TITLE
Fix class attributes in documentation

### ISSUE THREAD

**Issue by davfsa** [hikari-py/hikari#45]
Class/instance attributes should follow the format in the events modules for consistency and accessibility.

Stuff in `hikari.events` now has the correct style of docstring - everything that doesn't just return None has a `Returns`, and stuff uses an imperative mood i.e. <verb> <description>. This includes attributes (`foo: Bar = attr.ib()`) which have the `"""docstring"""` beneath it.

For example. https://nekokatt.github.io/hikari/hikari/events/typing_events.html#hikari.events.typing_events.GuildTypingEvent.member

---

Almost everything in hikari.models is far less cohesive, often starting weird sentences like `Whether your foo is enabled or not` instead of "Return `builtins.True` if foo is enabled."

This issue is to sort all of that documentation out and make it consistent.

- Run `nox -spdoc` to generate the html docs in `public/hikari`
- Run `nox -sflake8` and `nox -sreformat-code` to ensure formatting and wording is correct (this doesn't check attribute docstrings currently, so be careful).

**Comment by nekokatt** [comment]
PR to PyDocStyle perhaps?

**Comment by davfsa** [comment]
Closing for now, might open if I see fit later on
