### ISSUE TITLE
protocol.Protocol isn't runtime generic

### ISSUE THREAD

**Issue by FasterSpeeding** [hikari-py/hikari#467]
### Steps to reproduce
run this code on while targetting master
```py
import typing

from hikari.internal import protocol

TypeT = typing.TypeVar("TypeT")

protocol.Protocol[TypeT]
```

### Expected Result
It should pass like the following equivalent code would

```py
import typing

TypeT = typing.TypeVar("TypeT")

typing.Protocol[TypeT]
```

### Actual Result
It errors with the following traceback
```py
Traceback (most recent call last):
  File "C:\Users\...\PycharmProjects\hikari\bored.py", line 7, in <module>
    protocol.Protocol[TypeT]
  File "C:\Python39\lib\typing.py", line 262, in inner
    return func(*args, **kwds)
  File "C:\Python39\lib\typing.py", line 980, in __class_getitem__
    _check_generic(cls, params, len(cls.__parameters__))
  File "C:\Python39\lib\typing.py", line 196, in _check_generic
    raise TypeError(f"{cls} is not a generic class")
TypeError: <class 'hikari.internal.protocol.Protocol'> is not a generic class
```

### System info
```
hikari (SNAPSHOT) [HEAD]
CPython 3.9.1 MSC v.1927 64 bit (AMD64)
Windows YangWen-li 10 10.0.21277 AMD64 AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
```

### Further info
targeting the master branch

### Checklist

- [x] I have made sure to remove ANY sensitive information (bot token, passwords,
      credentials, personal details, etc).
- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by davfsa** [comment]
We can just use `typing.Protocol` for types instead of `procotol.Protocol`. I have been looking into implementing it and to do so I have to use a lot of typing internals that I'm not overly comfortable doing. I can add a disclaimer to the class for this.

**Comment by FasterSpeeding** [comment]
> We can just use `typing.Protocol` for types instead of `procotol.Protocol`. I have been looking into implementing it and to do so I have to use a lot of typing internals that I'm not overly comfortable doing. I can add a disclaimer to the class for this.

Wouldn't that kind of funk up the public interface around protocols quite a bit since then you'd have protocol classes which users can extend while keeping them as protocols and others which they won't (since they'd be relying on an internal class we provide which isn't intended to be directly used publicly since internal)
