### ISSUE TITLE
Drop support for stackless python and provide Cython speedups

### ISSUE THREAD

**Issue by davfsa** [hikari-py/hikari#535]
Stackless python has not been updated in over a year and the last fully supported version is 3.7. We should consider removing it and focusing on other alternatives like Cython (currently waiting on https://github.com/cython/cython/pull/3939 and https://github.com/cython/cython/pull/3691 for it to hopefully work correctly with hikari)

**Comment by FasterSpeeding** [comment]
Fine with me, shouldnt be hard to remove anyway

**Comment by davfsa** [comment]
https://github.com/hikari-py/hikari/pull/704#issuecomment-899040840
