### ISSUE TITLE
Implement threads

### ISSUE THREAD

**Issue by davfsa** [hikari-py/hikari#623]
https://discord.com/developers/docs/topics/threads
https://discord.com/developers/docs/change-log#api-v9

This should be done with the full switch to v9 when it is out

**Comment by davfsa** [comment]
This can now be implemented if anybody would like to:

![image](https://user-images.githubusercontent.com/29100934/123813753-736c5a00-d8f5-11eb-84b1-2870b86c54a0.png)

**Comment by FasterSpeeding** [comment]
Btw I do have code for this locally
