### ISSUE TITLE
Sticker#pack_id is optional

### ISSUE THREAD

**Issue by A5rocks** [hikari-py/hikari#680]
### Steps to reproduce
https://github.com/hikari-py/hikari/blob/bcf866e06e5ed961489142db85999d3a535f49aa/hikari/messages.py#L258-L259

### Expected Result
https://github.com/discord/discord-api-docs/pull/3127/files#diff-160acb4654c611c67c4ee46b2ce5dda2be82212af8d1d00cd0256ef6edda1e95R341

### Checklist

- [x] I have made sure to remove ANY sensitive information (bot token, passwords,
      credentials, personal details, etc).
- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by FasterSpeeding** [comment]
This isn't a bug anymore, they've stopped sending the "stickers" field on messages all together
