### ISSUE TITLE
Toggle to allow n amount of automatic-retries for internal server errors

### ISSUE THREAD

**Issue by FasterSpeeding** [hikari-py/hikari#747]
### Summary
For this feature request I propose that an option be added to the rest client to allow for automatic retries on some if not all 5xx error codes either unlimited or up to a certain number of retries.

### Problem
Right now the behaviour of raising on 500s can lead to the code consuming the REST client having to put a ton of messy retry logic around requests to handle both 500s and ratelimited errors.

### Ideal implementation
Add an argument to the rest client and relevant bot clients which defaults to idk maybe 5 retires and allows for specify the amount of times the lib should automatically retry on a 5xx error code (with it likely using an exponential back off strategy between requests) which can be set to 0 to signify that it should always raise. Alternatively this argument could be a boolean  argument where true signifies unlimited retries on 5xx and False signifies always raise

### Checklist

- [ ] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by ahnaf-zamil** [comment]
Hmm, seems like a good idea. I'ma start working on it, please assign this issue to me
