### ISSUE TITLE
Add missing `old_x` fields in events

### ISSUE THREAD

**Issue by davfsa** [hikari-py/hikari#766]
There is currently a bit of inconsistency in the `old_x` fields in the update and delete events for objects we cache

Examples that I have seen are (there might be more):
- *MessageDeleteEvent
- ~~*ChannelDeleteEvent (no need, discord send the info for this one)~~
- GuildLeaveEvent (solved by #806)

**Comment by ashwinvin** [comment]
I would like to do this.

**Comment by NobodyForYouCreator** [comment]
Hey, working with MemberDeleteEvent and it doesn't return old_member if member joined after bot start

- MemberDeleteEvent

**Comment by davfsa** [comment]
> 
> 
> Hey, working with MemberDeleteEvent and it doesn't return old_member if member joined after bot start
> 
>     * MemberDeleteEvent

That is related to the state of the cache. This issue is to track the absence of `old_x` fields completely missing from the object, which is currently only for `*MessageDeleteEvent`. You may not have the correct intents for that, which is why it is missing.

Please join the Discord server to get more help there :)

Invite: https://discord.gg/Jx4cNGG
