### ISSUE TITLE
Implement the new application command types

### ISSUE THREAD

**Issue by FasterSpeeding** [hikari-py/hikari#794]
### Summary
Implement the new application command types

### Problem
Implement the new application command types

### Ideal implementation
Implement the new application command types

### Checklist

- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by FasterSpeeding** [comment]
context menus

**Comment by Xyaren** [comment]
Does this also include these ?
- [User Commands](https://discord.com/developers/docs/interactions/application-commands#user-commands)
- [Messsage Commands](https://discord.com/developers/docs/interactions/application-commands#message-commands)

**Comment by davfsa** [comment]
> Does this also include these ?
> 
>     * [User Commands](https://discord.com/developers/docs/interactions/application-commands#user-commands)
> 
>     * [Messsage Commands](https://discord.com/developers/docs/interactions/application-commands#message-commands)

Yep, context menus include both of those

**Comment by thenishantsapkota** [comment]
@FasterSpeeding Any progress on this?
