### ISSUE TITLE
Package Installation Issue

### ISSUE THREAD

**Issue by remiteeple** [hikari-py/hikari#846]
### Steps to reproduce

1. Attempt to install via "python3 -m poetry add hikari"

### Expected Result

Successful installation of the package.

### Actual Result

Unsuccessful installation of the package.

```
--> python3 -m poetry add hikari
Using version ^2.0.0-alpha.103 for hikari

Updating dependencies
Resolving dependencies...

  SolverProblemError

  The current project's Python requirement (>=3.8,<4.0) is not compatible with some of the required packages Python requirement:
    - hikari requires Python >=3.8.0,<3.11, so it will not be satisfied for Python >=3.11,<4.0
  
  Because no versions of hikari match >2.0.0-alpha.103,<3.0.0
   and hikari (2.0.0.dev103) requires Python >=3.8.0,<3.11, hikari is forbidden.
  So, because repl-python3-rectangularfortunatedesigners depends on hikari (^2.0.0-alpha.103), version solving failed.

  at /opt/virtualenvs/python3/lib/python3.8/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For hikari, a possible solution would be to set the 'python' property to ">=3.8,<3.11"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
exit status 1
```

### System info

Python 3.8.2

### Further info

Easy to consistently replicate on replit.com.

### Checklist

- [X] I have made sure to remove ANY sensitive information (bot token, passwords,
      credentials, personal details, etc).
- [X] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by davfsa** [comment]
This is not really a bug but it is caused by something we did intentionally. We top cap the maximum python version we support to the latest available. This is done to ensure compatibility throughout all python versions we support. In poetry, specifying `^3.8` will be translated to `>=3.8,<4.0`, but hikari only (as of current releases version) allows only until 3.10.

You will have to set your python version in poetry to `>=3.8,<3.11` to allow it to install.

**Comment by remiteeple** [comment]
I understand it's not a bug, just figured I should inform you about it in case it was not intentional.  Since it is I'll close the issue.
