### ISSUE TITLE
Add nox to dev-requirements

### ISSUE THREAD

**Issue by parafoxia** [hikari-py/hikari#883]
### Summary
It would make contributing to hikari a smoother experience if nox was actually installed as part of the dev reuqirements. It's a small change, but there's no reason it shouldn't be there (at least to my knowledge).

### Problem
People have to install nox separately. If they don't know what's going on when running nox, they may submit untested contributions.

### Ideal implementation
Something in the dev-requirements.txt. ~~Maybe also add a pytest patch in there too for being able to run tests on 3.11.~~

### Checklist
- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by FasterSpeeding** [comment]
nox can be added sure but its not an issue with pytest which is blocking 3.11 supports, its yarl which is an indirect dev dependency and doesn't build on 3.11 rn

**Comment by parafoxia** [comment]
Ah okay cool. I'll just get a PR going to add nox then.
