### ISSUE TITLE
Subclass OwnUser doesn't properly __eq__ compare to UserImpl 

### ISSUE THREAD

**Issue by dragonpaw** [hikari-py/hikari#980]
### Steps to reproduce

I observed today that OwnUser and UserImpl objects don't seem to compare correctly, and was wondering if I should open this as an issue on GitHub?

In my case, I was trying to scan old messages in a channel for ones the bot itself had sent, where I used the property of the shard ready event to get my bot_user:
```python
if message.author == hikari.ShardReadyEvent.my_user:
  # This always compares as false.

if message.author.id == hikari.ShardReadyEvent.my_user.id:
  # This behaves as I'd expect.
 ```

It seems to be that the custom `__eq__` on Unique doesn't handle when one of the two types is a subclass of the other, since it does a strict type match before comparing Snowflakes

### Expected result

I'd expect `if message.author == hikari.ShardReadyEvent.my_user` to be True

### Actual result

message.author == hikari.ShardReadyEvent.my_user is False, but if I compare the id's, they are the same.

### System info

```shell
hikari (2.0.0.dev105) [a3825788]
located at /Users/ash/.pyenv/versions/discord-bot/lib/python3.9/site-packages/hikari
CPython 3.9.4 Clang 12.0.0 (clang-1200.0.32.29)
Darwin Ashs-MacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64 i386
```

### Checklist

- [X] I have made sure to remove ANY sensitive information (bot token, passwords, credentials, personal details, etc.).
- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by Jonxslays** [comment]
I wouldn't necessarily consider this a bug, as I would expect objects of different types to compare as not equal which is the current behavior. 

I am not against this niche use case though and am curious on other peoples thoughts.

**Comment by Forbidden-A** [comment]
> I wouldn't necessarily consider this a bug, as I would expect objects of different types to compare as not equal which is the current behavior. 
> 
> I am not against this niche use case though and am curious on other peoples thoughts. 

My thoughts are, look at the rest of hikari's design if it makes sense to do it this way then it should be done if not then you can just use .id

**Comment by davfsa** [comment]
Just to clarify, this is a bug. Should be comparing unique objects by their ID only (some specific cases do exist that break this rule). I suspect the issue is with UserImpl rather than OwnUser, but will fix.

Ty for the report!

**Comment by dragonpaw** [comment]
> I wouldn't necessarily consider this a bug, as I would expect objects of different types to compare as not equal which is the current behavior. 

In most cases, I absolutely agree with you. I would expect, for example, an Emoji to never be __eq__ to a Message or a User. But here, I'd kinda expected, as a new developer to the framework, that both would be using the same, or close enough, User classes to still be comparable. I guess, for me, conceptually, a User is a User, no matter which method I used to look them up, and as such a should be able to ask "is the user that wrote this message the same as the user that I am?" Kinda like how in Django, a User I pull from the request object as `request.user` can be compared to a User I just queried back from the db. While it's two different instances of User, gotten two very different ways, the class knows to compare them by pk. So I didn't intuitively expect that the "who am I" function would return a different class entirely of User than one on a message. (I'm sure there's a perfectly logical reason having to do with oddities of the Discord api for why this is, but it's not obvious or intuitive to someone building their first bot.)

(Kinda like how you can't use == to compare strings in Java. If you know, you can avoid the pitfall, but super unintuitive at first and every new person stumbles over it.)

**Comment by dragonpaw** [comment]
> Just to clarify, this is a bug. [...]
> 
> Ty for the report!

Absolutely. And thank you for taking the time to consider this ticket, and for all the hard work you, and every other contributor, has done on this project. It looks like an awesome library and I'm very thankful for your efforts.
